import { StyleSheet } from 'react-native';
import { width } from '../../../../Config/Layout';
import { PrimaryColor } from '../../../../Config/ColorPalette';

const styles = StyleSheet.create({
  Container: {
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    width,
    backgroundColor: '#F8F8F9',
  },
  View: {
    alignSelf: 'center',
    alignItems: 'flex-start',
    backgroundColor: '#F8F8F9',
    width: width + 20,
    padding: 10,
    marginTop: 10,
  },
  ViewText: {
    fontSize: 16,
    fontWeight: '600',
    marginHorizontal: 16,
    color: '#868991',
    marginVertical: 10,
  },
  ViewTextPicker: {
    fontSize: 16,
    fontWeight: '600',
    color: '#868991',
    marginHorizontal: 16,
  },
  ViewTextPickerFirst: {
    fontSize: 16,
    fontWeight: '600',
    color: '#868991',
    marginHorizontal: 2,
  },
  Title: {
    fontSize: 18,
    fontWeight: '500',
    marginHorizontal: 16,
    padding: 5,
  },
  Cancel: {
    fontSize: 14,
    fontWeight: '500',
    color: '#E8505B',
  },
  AddButton: {
    padding: 10,
    marginVertical: 30,
  },
  AddButtonText: {
    color: PrimaryColor,
    fontSize: 16,
    fontWeight: '600',
  },
  ButtonAdd: {
    backgroundColor: PrimaryColor,
    flexDirection: 'row',
    width: width - 20,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: PrimaryColor,
    height: 50,
    padding: 9,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 2,
    elevation: 2,
    marginTop: 30,
    alignSelf: 'center',
  },
  ButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  Picker: {
    width,
    fontWeight: 'bold',
    fontSize: 16,
    backgroundColor: 'red',
    flex: 1,
  },
  modal: {
    backgroundColor: 'rgba(	15	,20	,50, 0.5)',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  Modal: {
    backgroundColor: 'rgba(	15	,20	,50, 0.5)',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  picker: {
    width,
  },
  modalContainer: {
    width,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    margin: 10,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 2,
    elevation: 2,
  },
  ModalButton: {
    backgroundColor: PrimaryColor,
    flexDirection: 'row',
    width: width - 100,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: PrimaryColor,
    height: 50,
    padding: 9,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 2,
    elevation: 2,
    marginHorizontal: 20,
  },
  inputTime: {
    alignItems: 'flex-start',
    marginHorizontal: 16,
    margin: 2,
    padding: 5,
    borderBottomWidth: 1,
    borderColor: '#868991',
  },
  MainView: {
    width: width - 33,
    marginVertical: 5,
    borderBottomWidth: 1,
    borderColor: '#868991',
  },
  ViewAlignContent: { alignItems: 'flex-start', justifyContent: 'center' },
  ShowMoreView: {
    width,
    marginVertical: 5,
  },
  PickerView: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 1,
    borderColor: '#868991',
    marginHorizontal: 16,
  },
  ViewRow: { flexDirection: 'row' },
  SelectView: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 1,
    borderColor: '#868991',
    marginHorizontal: 16,
  },
  MarginV: {
    width,
    marginVertical: 5,
  },
  FlexOne: { flex: 1 },
  TextFont: { fontWeight: '600', fontSize: 16 },
});

export default styles;
