import { StyleSheet, I18nManager } from 'react-native'
import { width, height } from '../../../../Config/Layout'
import {
  PrimaryColor,
  SecondaryText,
  GrayColor,
  LightText,
  PrimaryBorder,
  SecondaryColor,
} from '../../../../Config/ColorPalette'

const styles = StyleSheet.create({
  about: {
    width: width + 20,
    flex: 1,
    marginTop: 25,
  },
  aboutE: {
    borderBottomWidth: 1,
    borderColor: '#DFE0E3',
    width: width + 20,
    alignItems: 'flex-start',
  },
  aboutB: {
    backgroundColor: '#F8F8F9',
    flex: 1,
  },
  aboutButton: {
    width: width + 20,
    borderBottomColor: '#DFE0E3',
    borderBottomWidth: 1,
    padding: 15,
    flexDirection: 'row',
  },
  rightText: {
    fontWeight: '500',
    fontSize: 16,
    marginHorizontal: 15,
  },
  leftText: {
    fontWeight: '500',
    fontSize: 16,
    marginHorizontal: 10,
    color: '#859881',
  },
  aboutButtonLog: {
    width: width + 20,
    padding: 15,
    flexDirection: 'row',
    backgroundColor: '#fff',
  },
  leftTextLog: {
    fontWeight: '500',
    fontSize: 16,
    marginHorizontal: 10,
    color: '#E8505B',
  },
  aboutT: {
    fontSize: 18,
    marginHorizontal: 16,
    marginBottom: 12,
    fontWeight: '500',
  },
  warning: {
    width,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  modalContainer: {
    width,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    margin: 10,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 2,
    elevation: 2,
  },
  ModalButton: {
    backgroundColor: PrimaryColor,
    flexDirection: 'row',
    width: width - 100,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: PrimaryColor,
    height: 50,
    padding: 9,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 2,
    elevation: 2,
    marginHorizontal: 20,
    marginVertical: 20,
  },
  modal: {
    backgroundColor: 'rgba(	15	,20	,50, 0.5)',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  ButtonView: {
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
    width,
    alignSelf: 'center',
  },
  Button: {
    backgroundColor: PrimaryColor,
    flexDirection: 'row',
    width,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: PrimaryColor,
    height: 50,
    padding: 9,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 2,
    elevation: 2,
    marginBottom: 30,
  },
  ButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  Container: {
    flex: 1,
    alignItems: 'center',
  },
  ButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  ButtonViewModal: {
    flexDirection: 'row',
    width,
    justifyContent: 'space-around',
    marginTop: 60,
  },
  NotButton: {
    backgroundColor: SecondaryColor,
    flexDirection: 'row',
    width: 165,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: SecondaryColor,
    height: 50,
    padding: 9,
    justifyContent: 'center',
    alignItems: 'center',
  },
  ButtonModal: {
    backgroundColor: PrimaryColor,
    flexDirection: 'row',
    width: 165,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: PrimaryColor,
    height: 50,
    padding: 9,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 2,
    elevation: 2,
  },
  NotButtonText: {
    color: PrimaryColor,
    fontWeight: 'bold',
    fontSize: 16,
  },
  ButtonTextModal: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
})

export default styles
