import { StyleSheet, I18nManager } from 'react-native'
import { width } from '../../../../Config/Layout'
import { PrimaryColor, SecondaryText } from '../../../../Config/ColorPalette'

const styles = StyleSheet.create({
  about: {
    width: width + 20,
    flex: 1,
  },
  aboutE: {
    borderBottomWidth: 1,
    borderColor: '#DFE0E3',
    width: width + 20,
    alignItems: 'flex-start',
  },
  aboutB: {
    backgroundColor: '#F8F8F9',
    flex: 1,
  },
  aboutButton: {
    width: width + 20,
    borderBottomColor: '#DFE0E3',
    borderBottomWidth: 1,
    padding: 15,
    flexDirection: 'row',
  },
  rightText: {
    fontWeight: '500',
    fontSize: 16,
    marginHorizontal: 15,
  },
  leftText: {
    fontWeight: '500',
    fontSize: 16,
    marginHorizontal: 10,
    color: '#859881',
  },
  LanguageSettingsText: {
    fontWeight: '500',
    fontSize: 16,
    marginHorizontal: 10,
  },
  aboutButtonLog: {
    width: width + 20,
    padding: 15,
    flexDirection: 'row',
    backgroundColor: '#fff',
  },
  leftTextLog: {
    fontWeight: '500',
    fontSize: 16,
    marginHorizontal: 10,
    color: '#E8505B',
  },
  aboutT: {
    fontSize: 18,
    marginHorizontal: 16,
    marginBottom: 12,
    fontWeight: '500',
  },
  warning: {
    width,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  modalContainer: {
    width,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    margin: 10,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 2,
    elevation: 2,
  },
  ModalButton: {
    backgroundColor: PrimaryColor,
    flexDirection: 'row',
    width: width - 100,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: PrimaryColor,
    height: 50,
    padding: 9,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 2,
    elevation: 2,
    marginHorizontal: 20,
    marginVertical: 20,
  },
  modal: {
    backgroundColor: 'rgba(	15	,20	,50, 0.5)',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  ButtonView: {
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
    width,
    alignSelf: 'center',
  },
  Button: {
    backgroundColor: PrimaryColor,
    flexDirection: 'row',
    width,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: PrimaryColor,
    height: 50,
    padding: 9,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 2,
    elevation: 2,
    marginBottom: 30,
  },
  ButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  Container: {
    flex: 1,
    alignItems: 'center',
  },
  ButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  container: {
    flex: 1,
    backgroundColor: '#fff',
    // justifyContent: 'center',
    alignItems: 'center',
  },
  KeyboardAvoidingView: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  error: {
    textAlign: 'center',
    color: '#E8505B',
    fontSize: 16,
    marginHorizontal: 29,
    marginVertical: 10,
  },
  inputPhone: {
    textAlign: I18nManager.isRTL ? 'right' : 'left',
    height: 45,
  },
  input: {
    backgroundColor: '#fff',
    height: 45,
    width,
    borderColor: '#DFE0E3',
    borderWidth: 1,
    borderRadius: 5,
    marginBottom: 10,
    padding: 5,
    textAlign: I18nManager.isRTL ? 'right' : 'left',
  },
  inputPassword: {
    backgroundColor: '#fff',
    height: 45,
    width,
    borderColor: SecondaryText,
    borderWidth: 1,
    borderRadius: 5,
    padding: 5,
    textAlign: I18nManager.isRTL ? 'right' : 'left',
  },
  HidePassword: {
    position: 'absolute',
    alignSelf: 'center',
    marginVertical: 10,
    right: 10,
  },
  Button: {
    backgroundColor: PrimaryColor,
    flexDirection: 'row',
    width,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: PrimaryColor,
    marginBottom: 12,
    height: 50,
    padding: 9,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 2,
    elevation: 2,
    marginTop: 20,
  },
  ButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  ForgotContainer: {
    width,
    alignItems: 'flex-end',
    marginTop: 10,
  },
  ForgotText: {
    color: SecondaryText,
  },
  Register: {
    flexDirection: 'row',
    marginTop: 30,
  },
  Member: {
    color: SecondaryText,
  },
  RegisterText: {
    color: PrimaryColor,
    textDecorationLine: 'underline',
    marginLeft: 5,
  },
  Terms: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  and: {
    color: SecondaryText,
  },
  Scroll: {
    flex: 1,
  },
})

export default styles
