import { StyleSheet, I18nManager } from 'react-native'
import { width, height } from '../../../../Config/Layout'
import { PrimaryColor, LightText, SecondaryColor, GrayColor } from '../../../../Config/ColorPalette'

const styles = StyleSheet.create({
  Container: {
    justifyContent: 'center',
    alignItems: 'flex-start',
    width,
    alignSelf: 'center',
  },
  modal: {
    backgroundColor: 'rgba(	15	,20	,50, 0.5)',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  Container: {
    backgroundColor: '#fff',
    width: width - 10,
    borderRadius: 6,
  },
  Body: {
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
  },
  Header: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: SecondaryColor,
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    padding: 10,
  },
  HeaderText: {
    fontSize: 16,
    fontWeight: '500',
    color: LightText,
  },
  BodyText: {
    fontSize: 16,
    fontWeight: '500',
    color: LightText,
    textAlign: 'center',
    marginVertical: 30,
    marginHorizontal: 10,
  },
  Button: {
    backgroundColor: PrimaryColor,
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 15,
    borderRadius: 6,
    padding: 10,
    marginHorizontal: 20,
  },
  ButtonDisable: {
    backgroundColor: '#cccccc',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 15,
    borderRadius: 6,
    padding: 10,
    marginHorizontal: 20,
  },
  ButtonText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#fff',
  },
  BodyTextDate: {
    fontSize: 16,
    fontWeight: 'bold',
    color: GrayColor,
    textAlign: 'center',
    marginVertical: 5,
    marginHorizontal: 10,
  },
  BodyTextDateTop: {
    fontSize: 16,
    fontWeight: 'bold',
    color: GrayColor,
    textAlign: 'center',
    marginTop: 10,
    marginHorizontal: 10,
    marginBottom: 5,
  },
  BodyTextTime: {
    fontSize: 16,
    fontWeight: '600',
    color: LightText,
    textAlign: 'center',
    marginVertical: 5,
    marginHorizontal: 10,
  },
  BodyTextTimeEnd: {
    fontSize: 16,
    fontWeight: '600',
    color: LightText,
    textAlign: 'center',
    marginTop: 5,
    marginHorizontal: 10,
    marginBottom: 20,
  },
  Image: {
    backgroundColor: PrimaryColor,
    width: 150,
    height: 150,
    borderRadius: 75,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 5,
    marginVertical: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 5,
    elevation: 5,
  },
  tinyLogo: {
    width: 150,
    height: 150,
    borderRadius: 75,
    borderWidth: 1,
    borderColor: PrimaryColor,
  },
  closebutton: {
    position: 'absolute',
    top: 5,
    left: 5,
    // backgroundColor: PrimaryColor,
    padding: 5,
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
})

export default styles
