import { StyleSheet, I18nManager } from 'react-native'
import { width, height } from '../../../../Config/Layout'
import {
  PrimaryColor,
  SecondaryText,
  GrayColor,
  LightText,
  PrimaryBorder,
} from '../../../../Config/ColorPalette'

const styles = StyleSheet.create({
  Container: {
    justifyContent: 'center',
    alignItems: 'flex-start',
    width,
    alignSelf: 'center',
  },
  Button: {
    backgroundColor: PrimaryColor,
    flexDirection: 'row',
    width: width - 20,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: PrimaryColor,
    height: 50,
    padding: 9,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 2,
    elevation: 2,
    marginBottom: 30,
    alignSelf: 'center',
  },
  ButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  Title: {
    fontWeight: '500',
    fontSize: 20,
    marginHorizontal: 16,
    marginTop: 20,
  },
  About: {
    fontWeight: '500',
    fontSize: 14,
    textAlign: 'left',
    marginHorizontal: 16,
    marginVertical: 6,
    color: '#868991',
  },

  Message: {
    fontWeight: '500',
    fontSize: 16,
    marginHorizontal: 16,
    marginTop: 20,
  },
  TextInput: {
    width: width - 20,
    alignSelf: 'center',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#4C4F56',
    marginHorizontal: 16,
    marginVertical: 16,
    padding: 5,
    height: 100,
    textAlign: I18nManager.isRTL ? 'right' : 'left',
  },
  modalContainer: {
    width,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
    margin: 10,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 2,
    elevation: 2,
  },
  ModalButton: {
    backgroundColor: PrimaryColor,
    flexDirection: 'row',
    width: width - 100,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: PrimaryColor,
    height: 50,
    padding: 9,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 2,
    elevation: 2,
    marginHorizontal: 20,
    marginVertical: 20,
  },
  modal: {
    backgroundColor: 'rgba(	15	,20	,50, 0.5)',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  Slogan: {
    textAlign: 'center',
    color: LightText,
    fontSize: 16,
    marginHorizontal: 29,
    marginVertical: 15,
  },
  Logo: {
    width,
    height: height / 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tinyLogo: {
    height: height / 10,
    resizeMode: 'contain',
  },
})

export default styles
